services:
  postgres:
    image: postgres:15
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
      - "./init-test-db.sh:/docker-entrypoint-initdb.d/init-test-db.sh"
    environment:
      - POSTGRES_USER=femto
      - POSTGRES_PASSWORD=femto
      - POSTGRES_DB=axum_boilerplate

  pgadmin:
    image: dpage/pgadmin4:9
    restart: "no"
    ports:
      - "8083:8083"
    volumes:
      - "pgadmin:/var/lib/pgadmin"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=8083

volumes:
  postgres:
  pgadmin:
